#!/usr/bin/env python3
"""Admit one descriptive reserved run after valid pilot, never allocate alpha."""
import json
from audit_release import ROOT,sha,write
from study_v2 import V2
FILES=['analysis/hexar_external/audit_inventory_v2.py','analysis/hexar_external/numerical_audit_v2.py','analysis/hexar_external/verify_v2.py','analysis/hexar_external/study_v2.py','analysis/hexar_external/build_v2_packets.py','analysis/hexar_external/build_references_v2.py','analysis/hexar_external/run_v2.py','analysis/hexar_external/annotate_v2.py','analysis/hexar_external/report_v2.py','docs/hexar_external/v2/ENDPOINT.md','docs/hexar_external/prompt_calibration_v1.txt','docs/hexar_external/v2/annotation_amendment.txt','data/hexar_external/v2/qualification/freeze.json','data/hexar_external/v2/qualification/qualification-result.json','data/hexar_external/v2/development/references.json','data/hexar_external/v2/development/packets.json','data/hexar_external/v2/development/results.json','data/hexar_external/audit/source_data_manifest.json','data/hexar_external/replay/native-parity.json']
def main():
 assert json.loads((V2/'qualification/qualification-result.json').read_text())['status']=='QUALIFIED'
 pilot=json.loads((V2/'development/results.json').read_text());assert pilot['independent_recordings']==6
 annotation=json.loads((V2/'development/annotation/annotation_summary.json').read_text())
 assert annotation['qualified_completed']>=.9*annotation['n_responses']
 value={'schema':'hexar-descriptive-study-freeze/v2','created_date':'2026-09-30','status':'DESCRIPTIVE_ONLY_NO_CONFIRMATORY_ACTIVATION','primary':'HX-CONTRACT minus HX-PROMPT recording-mean useful supported-answer success','conditions':['intact','irrelevant_removal','diagnostic_removal'],'questions':'all three released navigation questions per recording','weights':'nine jobs equal within recording; recordings equal; known families balanced','split':'repetition 1 development; repetitions 2/3 reserved; all six navigation situations','n_reserved_recordings':12,'n_family_clusters':6,'mask':'one universal pre-derivation diagnostic channel removal; no family selection','references':'independent fixed packet-only rule, built before reserved generation, no production ontology/answer inspection','annotation':'current qualified Astra/high support pipeline plus qualified external amendment; A/B and disagreement-only C; developer blind atom inventory unqualified, spans and completeness audited','alpha_allocation_id':None,'alpha_allocated':0,'alpha_consumed':0,'p_value_allowed':False,'analysis':'registered descriptive paired recording t95 plus six-family sensitivity t95 and A/B label sensitivity; no generalization beyond known released families','model':'gpt-6-sol/high requested hosted config; weights and immutable backend unknown','contract':'pinned main core; deterministic component realization replacement; zero model calls','workers':2,'quality_retries':0,'technical_retries':0,'technical_disposition':'missing semantic score with full fixed denominator worst/best bounds; pilot admission requires at least 90% completed qualified labels, not favorable scores or a complete-case effect','pilot_effect':pilot['primary_effect'],'pilot_discordance':{k:pilot[k] for k in ('favorable_recordings','unfavorable_recordings','tied_recordings')},'power_limit':'At alpha .01 an independent 12-pair sign test requires 11 of 12 favorable non-tied pairs; with six family clusters minimum two-sided sign-reversal p is .03125. Such a design cannot support a .01 family-level superiority claim; no extra masks manufacture N. No confirmatory test admitted.','file_hashes':{f:sha(ROOT/f) for f in FILES}}
 dest=V2/'study_freeze.json'
 if dest.exists():assert json.loads(dest.read_text())==value
 else:write(dest,value)
 print('DESCRIPTIVE_RESERVED_RUN_FROZEN_NO_ALPHA')
if __name__=='__main__':main()
