#!/usr/bin/env python3
"""Single prospective descriptive freeze after qualified compatibility pilot."""
import json
from audit_release import ROOT,sha,write
from study_v2 import V2
from verify_v3 import V3,qualified
FILES=['analysis/hexar_external/study_v2.py','analysis/hexar_external/build_v2_packets.py','analysis/hexar_external/build_references_v2.py','analysis/hexar_external/run_v2.py','analysis/hexar_external/annotate_v2.py','analysis/hexar_external/report_v2.py','analysis/hexar_external/audit_inventory_v2.py','analysis/hexar_external/numerical_audit_v2.py','analysis/hexar_external/verify_v3.py','analysis/hexar_external/build_v3_reserved.py','analysis/hexar_external/run_v3_reserved.py','analysis/hexar_external/annotate_v3.py','analysis/hexar_external/report_v3.py','docs/hexar_external/v2/ENDPOINT.md','docs/hexar_external/prompt_calibration_v1.txt','docs/hexar_external/v2/annotation_amendment.txt','docs/hexar_external/v3/sentinel_clarification.txt','docs/hexar_external/v3/PROSPECTIVE_INTERFACE_PILOT.md','data/hexar_external/v3/qualification/freeze.json','data/hexar_external/v3/qualification/qualification-result.json','data/hexar_external/v3/annotation_binding.json','data/hexar_external/v3/development/annotation/annotation_summary.json','data/hexar_external/v2/development/results.json','data/hexar_external/v2/development/packets.json','data/hexar_external/v2/development/references.json','data/hexar_external/audit/source_data_manifest.json','data/hexar_external/audit/split.json','data/hexar_external/replay/native-parity.json']
def main():
 qualified();pilot=json.loads((V2/'development/results.json').read_text());assert pilot['independent_recordings']==6
 ann=json.loads((V3/'development/annotation/annotation_summary.json').read_text());assert ann['n_responses']==54 and ann['qualified_completed']>=.9*ann['n_responses']
 fresh=json.loads((V3/'development/run_summary.json').read_text());assert fresh['n_recordings']==6 and fresh['valid']==54 and fresh['technical_failures']==0
 value={'schema':'hexar-descriptive-study-freeze/v3','created_date':'2026-09-30','status':'DESCRIPTIVE_ONLY_NO_CONFIRMATORY_ACTIVATION','primary':'HX-CONTRACT minus HX-PROMPT recording-mean useful supported-answer success','endpoint_definition':'unchanged v2/ENDPOINT.md; correct useful outcome and one available diagnostic, no material unsupported assertion, appropriate unavailable-conclusion scope','conditions':['intact','irrelevant_removal','diagnostic_removal'],'questions':'all three released navigation questions per recording','weights':'nine jobs equal within recording, twelve physical recordings equal, six known families balanced','split':'repetition 1 development; repetitions 2/3 reserved, no family held out','n_reserved_recordings':12,'n_family_clusters':6,'methods':['HX-ORIGINAL','HX-PROMPT','HX-CONTRACT'],'mask':'same universal pre-derivation diagnostic-channel removal, clean state, original outcome/window preserved','references':'unchanged independently developed packet-only rules, built and released before reserved answers','annotation':'same qualified current Astra/high main prompt/schema/validator plus unchanged v2 semantic amendment and qualified v3 applicability clarification, A/B and disagreement-only C; developer blind inventory not qualified or human-validated','measurement_history':'retain v1 failure, v2 synthetic pass and full-query field-invalid pilot without retries/rescoring; v3 fresh fixture and all-family q1 compatibility pilot add no physical N and do not substitute q1 for scientific endpoint','technical_completion_gate':.9,'alpha_allocation_id':None,'alpha_allocated':0,'alpha_consumed':0,'p_value_allowed':False,'analysis':'one descriptive complete-recording paired mean/t95, six-family sensitivity t95, full fixed-denominator missing-label effect bounds as principal result when incomplete, A/B annotation sensitivity; no population-wide or confirmatory superiority','model':'same requested hosted gpt-6-sol/high model-backed conditions; weight digest and immutable backend unknown','contract':'same pinned core; deterministic component realization replacement, zero model calls','workers':2,'quality_retries':0,'technical_retries':0,'technical_disposition':'missing semantic scores with full fixed denominator worst/best bounds, separate extraction/model/annotation failures','pilot_effect':pilot['primary_effect'],'pilot_effect_bounds':pilot['primary_full_cohort_effect_bounds'],'pilot_discordance':{k:pilot[k] for k in ('paired_complete_recordings','favorable_recordings','unfavorable_recordings','tied_recordings')},'power_limit':'N=12 physical executions, six shared known-family clusters. At hypothetical alpha .01 a 12-pair sign test requires 11 favorable discordances; the minimum two-sided six-family sign-reversal p is .03125. No confirmatory test or alpha allocation is admitted; masks/queries/repetitions add no independent N. Pilot missing labels further limit precision.','file_hashes':{f:sha(ROOT/f) for f in FILES}}
 dest=V3/'study_freeze.json'
 if dest.exists():assert json.loads(dest.read_text())==value
 else:write(dest,value)
 print('V3_COMPLETE_RESERVED_DESCRIPTIVE_DESIGN_FROZEN_NO_ALPHA',flush=True)
if __name__=='__main__':main()
