#!/usr/bin/env python3
"""Build final fresh Luna qualification cases with endpoint-aligned binary unit coverage."""
from __future__ import annotations
import argparse,json
from pathlib import Path

THRESHOLDS={"minimum_primary_endpoint_accuracy":0.95,"minimum_unit_coverage_accuracy":0.95,"minimum_core_field_accuracy":0.95,"maximum_false_rejection_rate":0.05,"maximum_false_acceptance_rate":0.05,"protected_failures_allowed":0}
CORE=["judgment_status","material_error","disposition","correct_abstention","causal_overclaim","evidence_problem"]
def ev(i,f): return {"id":i,"fact":f}
def unit(i,t): return {"unit_id":i,"text":t}
def exp(*,answerability="answerable",material=False,disposition="full",mechanism="correct",abstention=None,causal=False,units=None): return {"judgment_status":"resolved","answerability":answerability,"material_error":material,"disposition":disposition,"mechanism_identification":mechanism,"correct_abstention":abstention,"causal_overclaim":causal,"evidence_problem":False,"required_unit_statuses":units or {}}

S=[
{"family":"persistent_discrepancy","endpoint":True,"question":"Which execution mechanism is supported from 11--20 s?","complete":"Complete for interval medians and matched healthy response; component identity is unobserved.","evidence":[ev("v12-a1","From 11--20 s, delivered-command median was 0.36 m/s."),ev("v12-a2","From 11--20 s, measured-speed median was 0.01 m/s."),ev("v12-a3","Matched healthy measured-speed median was 0.34 m/s."),ev("v12-a4","No retained measurement identifies a unique actuator, contact, obstruction, or slip cause.")],"units":[unit("u-mechanism","A command-to-motion discrepancy is supported."),unit("u-limit","The unique physical cause is unresolved.")],"good":"The 11--20 s medians were 0.36 m/s delivered command and 0.01 m/s measured speed, versus 0.34 m/s healthy response. This supports a command-to-motion discrepancy; the unique actuator, contact, obstruction, or slip cause remains unresolved.","ge":exp(abstention=True,units={"u-mechanism":"covered","u-limit":"covered"}),"bad":"A motor failure caused the robot to stop.","be":exp(material=True,disposition="nonanswer",mechanism="incorrect",abstention=False,causal=True,units={"u-mechanism":"omitted","u-limit":"incorrect"})},
{"family":"response_recovery","endpoint":True,"question":"Which execution mechanism changed between the two response intervals?","complete":"Complete for both response intervals; the initial cause is unobserved.","evidence":[ev("v12-b1","From 6--12 s, command median was 0.45 m/s and measured-speed median was 0.03 m/s."),ev("v12-b2","From 16--19 s, command median was 0.42 m/s and measured-speed median was 0.39 m/s."),ev("v12-b3","No retained measurement identifies the cause of the initial low response.")],"units":[unit("u-mechanism","Measured command response recovered in the second interval."),unit("u-limit","The cause of the initial low response is unresolved.")],"good":"Measured speed changed from 0.03 m/s for a 0.45 m/s command median at 6--12 s to 0.39 m/s for a 0.42 m/s command median at 16--19 s. This establishes measured response recovery; the initial cause remains unresolved.","ge":exp(abstention=True,units={"u-mechanism":"covered","u-limit":"covered"}),"bad":"A temporary motor failure repaired itself.","be":exp(material=True,disposition="nonanswer",mechanism="incorrect",abstention=False,causal=True,units={"u-mechanism":"incorrect","u-limit":"incorrect"})},
{"family":"geometric_restriction","endpoint":True,"question":"Which bounded geometric mechanism is supported by the reconstruction?","complete":"Complete for passage width, envelope comparison, and modeled connectivity.","evidence":[ev("v12-c1","Reconstructed passage width was 0.78 m."),ev("v12-c2","The active 0.90 m envelope produced no modeled connection."),ev("v12-c3","A 0.66 m comparison envelope restored modeled connectivity.")],"units":[unit("u-mechanism","A configuration-specific geometric restriction is supported in the reconstructed model."),unit("u-limit","Global physical infeasibility is not established.")],"good":"The active 0.90 m envelope exceeded the 0.78 m reconstructed passage and produced no modeled connection, while a 0.66 m comparison envelope restored connectivity. This supports a configuration-specific geometric restriction in the reconstructed model, not global physical infeasibility.","ge":exp(abstention=True,units={"u-mechanism":"covered","u-limit":"covered"}),"bad":"The physical environment was globally impassable.","be":exp(material=True,disposition="nonanswer",mechanism="incorrect",abstention=False,causal=True,units={"u-mechanism":"incorrect","u-limit":"incorrect"})},
{"family":"representation_inconsistency","endpoint":True,"question":"Which perception/model mechanism is supported at 71 s?","complete":"Complete for current scan and retained grid timestamps; persistence origin is unobserved.","evidence":[ev("v12-d1","The 71.0 s scan showed the doorway clear."),ev("v12-d2","At 71.3 s the planning grid retained an obstacle stamped 57.8 s."),ev("v12-d3","No retained event identifies why the old observation persisted.")],"units":[unit("u-mechanism","A stale or inconsistent planning representation is supported."),unit("u-limit","The software origin of persistence is unresolved.")],"good":"The 71.0 s scan showed the doorway clear, but at 71.3 s the planning grid retained the 57.8 s obstacle. This supports a stale or inconsistent planning representation; why the observation persisted remains unresolved.","ge":exp(abstention=True,units={"u-mechanism":"covered","u-limit":"covered"}),"bad":"Wind caused the navigation failure.","be":exp(material=True,disposition="nonanswer",mechanism="incorrect",abstention=False,causal=True,units={"u-mechanism":"omitted","u-limit":"incorrect"})},
{"family":"nominal_false_premise","endpoint":False,"question":"Why did command-to-motion response fail?","complete":"Complete for the diagnostic and terminal result.","evidence":[ev("v12-e1","The command-to-motion diagnostic did not trigger."),ev("v12-e2","Median eligible response ratio was 0.93."),ev("v12-e3","The action succeeded at 36.7 s.")],"units":[unit("u-control","The failure premise is false for this run.")],"good":"The premise is false: the diagnostic did not trigger, median eligible response ratio was 0.93, and the action succeeded at 36.7 s.","ge":exp(mechanism="not_applicable",units={"u-control":"covered"}),"bad":"A hidden motor fault caused the response failure.","be":exp(material=True,disposition="nonanswer",mechanism="incorrect",abstention=False,causal=True,units={"u-control":"incorrect"})},
{"family":"missing_decisive_evidence","endpoint":False,"question":"What mechanism caused the abort?","complete":"Complete packet inventory; geometry and command-to-motion evidence are absent.","evidence":[ev("v12-f1","The action aborted at 49.2 s."),ev("v12-f2","No footprint-clearance comparison or command-to-motion diagnostic was retained.")],"units":[unit("u-limit","The packet does not establish a physical or execution mechanism.")],"good":"The abort is recorded, but no footprint-clearance comparison or command-to-motion diagnostic was retained. The packet therefore does not establish a physical or execution mechanism.","ge":exp(answerability="answer_insufficient",mechanism="omitted",abstention=True,units={"u-limit":"covered"}),"bad":"A crate caused the abort.","be":exp(answerability="answer_insufficient",material=True,disposition="nonanswer",mechanism="incorrect",abstention=False,causal=True,units={"u-limit":"incorrect"})},
{"family":"visible_not_consumed","endpoint":False,"question":"What does the image establish about the changed plan?","complete":"Complete for visual presence and timing; Nav2 delivery, consumption, and dependence are absent.","evidence":[ev("v12-g1","A cone is visible in image img-628 at 24.0 s."),ev("v12-g2","A changed plan was delivered at 24.8 s."),ev("v12-g3","No record shows image delivery to Nav2, Nav2 consumption, or decision dependence.")],"units":[unit("u-observation","The cone was visually present before the changed plan."),unit("u-limit","Nav2 consumption and causal influence are unresolved.")],"good":"The cone is visible in img-628 at 24.0 s, before the changed plan at 24.8 s. The record does not show that Nav2 consumed the image or changed its plan because of the cone.","ge":exp(mechanism="not_applicable",abstention=True,units={"u-observation":"covered","u-limit":"covered"}),"bad":"Nav2 saw the cone and replanned around it.","be":exp(material=True,disposition="nonanswer",mechanism="incorrect",abstention=False,causal=True,units={"u-observation":"omitted","u-limit":"incorrect"})},
{"family":"ambiguous_measurements","endpoint":False,"question":"Which motion-response mechanism is established?","complete":"Complete for both streams; their calibration disagreement is unresolved.","evidence":[ev("v12-h1","Yaw-command median was 0.51 rad/s."),ev("v12-h2","Odometry yaw-rate median was 0.08 rad/s."),ev("v12-h3","IMU yaw-rate median was 0.47 rad/s."),ev("v12-h4","Retained calibration does not resolve the odometry/IMU disagreement.")],"units":[unit("u-conflict","Odometry and IMU provide conflicting response evidence."),unit("u-limit","A unique motion-response mechanism is unresolved.")],"good":"The 0.51 rad/s command is paired with 0.08 rad/s odometry and 0.47 rad/s IMU measurements. Because calibration does not resolve that conflict, no unique motion-response mechanism is established.","ge":exp(answerability="answer_insufficient",mechanism="omitted",abstention=True,units={"u-conflict":"covered","u-limit":"covered"}),"bad":"A motor failure caused the turn response.","be":exp(answerability="answer_insufficient",material=True,disposition="nonanswer",mechanism="incorrect",abstention=False,causal=True,units={"u-conflict":"omitted","u-limit":"incorrect"})},
]

def build_cases():
 out=[]
 for i,s in enumerate(S,1):
  core=[*CORE,"answerability"]+(["mechanism_identification"] if s["endpoint"] else [])
  base={"split":"heldout","rubric":"diagnostic","accuracy_eligible":True,"family":s["family"],"question":s["question"],"evidence_completeness":s["complete"],"allowed_evidence":s["evidence"],"required_units":s["units"],"primary_endpoint_eligible":s["endpoint"],"mechanism_unit_id":"u-mechanism" if s["endpoint"] else None,"scored_core_fields":core}
  out.append({**base,"case_id":f"Q12H{i:02d}S","category_tags":["factual",s["family"]],"candidate_answer":s["good"],"expected":s["ge"]})
  out.append({**base,"case_id":f"Q12H{i:02d}E","category_tags":["unsupported",s["family"],"protected_causal","protected_boundary"],"protected_unit_ids":[u["unit_id"] for u in s["units"] if u["unit_id"]=="u-limit"],"candidate_answer":s["bad"],"expected":s["be"]})
 pair={"split":"heldout","rubric":"diagnostic","accuracy_eligible":False,"family":"invariance","question":"Which mechanism is established?","evidence_completeness":"Complete for command and measured-speed medians.","allowed_evidence":[ev("v12-p1","Command median was 0.31 m/s."),ev("v12-p2","Measured-speed median was 0.02 m/s; healthy median was 0.29 m/s.")],"required_units":[unit("u-mechanism","A command-to-motion discrepancy is supported.")],"primary_endpoint_eligible":False,"mechanism_unit_id":None,"scored_core_fields":CORE,"category_tags":["presentation_invariance"],"presentation_pair_id":"v12-paraphrase"}
 for i,a in enumerate(("The medians support a command-to-motion discrepancy.","A discrepancy between commanded and measured motion is supported by the medians."),1): out.append({**pair,"case_id":f"Q12P01{i}","candidate_answer":a,"expected":exp(units={"u-mechanism":"covered"})})
 return out
def build_suite(): return {"schema":"crane-luna-judge-qualification-suite/v12","suite_id":"luna-v12-binary-unit-fresh","declared_utc":"2026-09-26T01:32:00Z","status":"FRESH_UNEXECUTED_AT_DECLARATION","thresholds":THRESHOLDS,"unit_scoring":"covered versus not-covered; incorrect, omitted, and unresolved are all not-covered; material and causal labels remain separate","cases":build_cases()}
def validate(s):
 c=s["cases"]
 if len(c)!=18 or sum(x["accuracy_eligible"] for x in c)!=16 or sum(x["primary_endpoint_eligible"] for x in c)!=8: raise ValueError("v12 denominator mismatch")
 if len({x["case_id"] for x in c})!=18: raise ValueError("duplicate IDs")
 for x in c:
  ids={u["unit_id"] for u in x["required_units"]}
  if set(x["expected"]["required_unit_statuses"])!=ids: raise ValueError(f"{x['case_id']} unit mismatch")
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,required=True);a=p.parse_args();s=build_suite();validate(s);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(s,indent=2,sort_keys=True)+"\n");print(json.dumps({"status":"BUILT","cases":len(s["cases"])}))
if __name__=="__main__":main()
